export interface DownloadTitles {
  partialDataset: string;
  fullDataset: string;
  download: string;
  includeMetadata: string;
  metadata: string;
  all: string;
  none: string;
  dataFormat: string;
  attributes: string;
  downloadType: string;
  dataset: string;
  idOptions: string;
  idOptionsDescription: string;
  nameOptions: string;
  nameOptionsDescription: string;
  idAndNameOptions: string;
  idAndNameOptionsDescription: string;
  close?: string;
  cancel?: string;
  datasetsToDownload?: string;
  rows?: string;
  filesWillBeDownloaded?: (count: number) => string;
  oneFilePerDataset?: string;
  downloadStartedTitle?: string;
  downloadStartedText?: (dataFormat: string) => string;
  downloadInProgressTitle?: (current: number, total: number) => string;
  downloadInProgressText?: (datasetName: string, dataFormat: string) => string;
  downloadSuccessTitle?: (dataFormat: string) => string;
  downloadSuccessMultipleTitle?: (count: number) => string;
  downloadSuccessText?: (fileName: string, rows: number) => string;
  downloadSuccessMultipleText?: (count: number) => string;
  downloadFailedTitle?: string;
  downloadFailedText?: (datasetName: string) => string;
  downloadFailedMultipleText?: (count: number) => string;
  downloadCancelActionText?: string;
  downloadRetryActionText?: string;
}
