---
excludes:
  paths:
    - pattern: 'package-lock.json'
      reason: 'BUILD_TOOL_OF'
  packages:
    - id: "NPM:@dev-statgpt/conversation-list:0.1.2"
    - id: "NPM:@dev-statgpt/conversation-view:0.1.2"
    - id: "NPM:@dev-statgpt/ui-components:0.1.2"
  scopes:
    - pattern: 'devDependencies'
      reason: 'DEV_DEPENDENCY_OF'
      comment: 'Packages for development only.'
license_choices:
  repository_license_choices:
    - given: 'GPL-2.0-only OR MIT'
      choice: 'MIT'
    - given: 'GPL-3.0-or-later OR MIT'
      choice: 'MIT'
