---
excludes:
  paths:
    - pattern: 'package-lock.json'
      reason: 'BUILD_TOOL_OF'
  scopes:
    - pattern: 'devDependencies'
      reason: 'DEV_DEPENDENCY_OF'
      comment: 'Packages for development only.'
    - pattern: '@statgpt/**'
      reason: 'DEV_DEPENDENCY_OF'
      comment: 'Packages for development only.'
resolutions:
  rule_violations:
    - message: "No license information is available for dependency \
        'NPM::@statgpt:shared-toolkit:0\\.0\\.1'\\."
      reason: 'CANT_FIX_EXCEPTION'
      comment: 'The dependency has MIT license in github repo'
